# Generated by Django 3.2.6 on 2021-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depress',
            name='sleep_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='depress',
            name='date',
            field=models.DateField(),
        ),
    ]
